name: hybrid_media
description: "The media library of the Hybrid SDK."
version: 0.0.1-dev.0
repository: "https://github.com/yanshouwang/hybrid_sdk"

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hybrid_media_platform_interface: ^0.0.1-dev.1
  hybrid_media_android: ^0.0.1-dev.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: hybrid_media_android
