name: hybrid_sdk
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0

workspace:
  - hybrid_ffi
  - hybrid_ffi/example
  - hybrid_logging
  - hybrid_os/hybrid_os_platform_interface
  - hybrid_os/hybrid_os_android
  - hybrid_os/hybrid_os_android/example
  - hybrid_os/hybrid_os_darwin
  - hybrid_os/hybrid_os_darwin/example
  - hybrid_os/hybrid_os_linux
  - hybrid_os/hybrid_os_linux/example
  - hybrid_os/hybrid_os_windows
  - hybrid_os/hybrid_os_windows/example
  - hybrid_os/hybrid_os
  - hybrid_os/hybrid_os/example
  - hybrid_ui
  - hybrid_ui/example
  - hybrid_usb
  - hybrid_usb/example
  - hybrid_vision/hybrid_vision_platform_interface
  - hybrid_vision/hybrid_vision_android
  - hybrid_vision/hybrid_vision_android/example
  - hybrid_vision/hybrid_vision_darwin
  - hybrid_vision/hybrid_vision_darwin/example
  - hybrid_vision/hybrid_vision
  - hybrid_vision/hybrid_vision/example
