// Autogenerated by jnigen. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:ffi' as ffi;
import 'dart:isolate' show ReceivePort;

import 'package:jni/internal_helpers_for_jnigen.dart';
import 'package:jni/jni.dart' as jni;

import '../net/Uri.dart' as uri_;

import '../os/Handler.dart' as handler_;

/// from: `android.database.ContentObserver`
class ContentObserver extends jni.JObject {
  @override
  late final jni.JObjType<ContentObserver> $type = type;

  ContentObserver.fromReference(
    jni.JReference reference,
  ) : super.fromReference(reference);

  static final _class = jni.JClass.forName(r'android/database/ContentObserver');

  /// The type which includes information such as the signature of this class.
  static const type = $ContentObserverType();
  static final _id_new0 = _class.constructorId(
    r'(Landroid/os/Handler;)V',
  );

  static final _new0 = ProtectedJniExtensions.lookup<
              ffi.NativeFunction<
                  jni.JniResult Function(
                      ffi.Pointer<ffi.Void>,
                      jni.JMethodIDPtr,
                      ffi.VarArgs<(ffi.Pointer<ffi.Void>,)>)>>(
          'globalEnv_NewObject')
      .asFunction<
          jni.JniResult Function(ffi.Pointer<ffi.Void>, jni.JMethodIDPtr,
              ffi.Pointer<ffi.Void>)>();

  /// from: `public void <init>(android.os.Handler handler)`
  /// The returned object must be released after use, by calling the [release] method.
  factory ContentObserver(
    handler_.Handler handler,
  ) {
    return ContentObserver.fromReference(_new0(_class.reference.pointer,
            _id_new0 as jni.JMethodIDPtr, handler.reference.pointer)
        .reference);
  }

  static final _id_deliverSelfNotifications = _class.instanceMethodId(
    r'deliverSelfNotifications',
    r'()Z',
  );

  static final _deliverSelfNotifications = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JniResult Function(
                ffi.Pointer<ffi.Void>,
                jni.JMethodIDPtr,
              )>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni.JniResult Function(
            ffi.Pointer<ffi.Void>,
            jni.JMethodIDPtr,
          )>();

  /// from: `public boolean deliverSelfNotifications()`
  bool deliverSelfNotifications() {
    return _deliverSelfNotifications(
            reference.pointer, _id_deliverSelfNotifications as jni.JMethodIDPtr)
        .boolean;
  }

  static final _id_onChange = _class.instanceMethodId(
    r'onChange',
    r'(Z)V',
  );

  static final _onChange = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JThrowablePtr Function(
                  ffi.Pointer<ffi.Void>,
                  jni.JMethodIDPtr,
                  ffi.VarArgs<($Int32,)>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni.JThrowablePtr Function(
              ffi.Pointer<ffi.Void>, jni.JMethodIDPtr, int)>();

  /// from: `public void onChange(boolean z)`
  void onChange(
    bool z,
  ) {
    _onChange(reference.pointer, _id_onChange as jni.JMethodIDPtr, z ? 1 : 0)
        .check();
  }

  static final _id_onChange1 = _class.instanceMethodId(
    r'onChange',
    r'(ZLandroid/net/Uri;)V',
  );

  static final _onChange1 = ProtectedJniExtensions.lookup<
              ffi.NativeFunction<
                  jni.JThrowablePtr Function(
                      ffi.Pointer<ffi.Void>,
                      jni.JMethodIDPtr,
                      ffi.VarArgs<($Int32, ffi.Pointer<ffi.Void>)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni.JThrowablePtr Function(ffi.Pointer<ffi.Void>, jni.JMethodIDPtr,
              int, ffi.Pointer<ffi.Void>)>();

  /// from: `public void onChange(boolean z, android.net.Uri uri)`
  void onChange1(
    bool z,
    uri_.Uri uri,
  ) {
    _onChange1(reference.pointer, _id_onChange1 as jni.JMethodIDPtr, z ? 1 : 0,
            uri.reference.pointer)
        .check();
  }

  static final _id_onChange2 = _class.instanceMethodId(
    r'onChange',
    r'(ZLandroid/net/Uri;I)V',
  );

  static final _onChange2 = ProtectedJniExtensions.lookup<
              ffi.NativeFunction<
                  jni.JThrowablePtr Function(
                      ffi.Pointer<ffi.Void>,
                      jni.JMethodIDPtr,
                      ffi.VarArgs<($Int32, ffi.Pointer<ffi.Void>, $Int32)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni.JThrowablePtr Function(ffi.Pointer<ffi.Void>, jni.JMethodIDPtr,
              int, ffi.Pointer<ffi.Void>, int)>();

  /// from: `public void onChange(boolean z, android.net.Uri uri, int i)`
  void onChange2(
    bool z,
    uri_.Uri uri,
    int i,
  ) {
    _onChange2(reference.pointer, _id_onChange2 as jni.JMethodIDPtr, z ? 1 : 0,
            uri.reference.pointer, i)
        .check();
  }

  static final _id_onChange3 = _class.instanceMethodId(
    r'onChange',
    r'(ZLjava/util/Collection;I)V',
  );

  static final _onChange3 = ProtectedJniExtensions.lookup<
              ffi.NativeFunction<
                  jni.JThrowablePtr Function(
                      ffi.Pointer<ffi.Void>,
                      jni.JMethodIDPtr,
                      ffi.VarArgs<($Int32, ffi.Pointer<ffi.Void>, $Int32)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni.JThrowablePtr Function(ffi.Pointer<ffi.Void>, jni.JMethodIDPtr,
              int, ffi.Pointer<ffi.Void>, int)>();

  /// from: `public void onChange(boolean z, java.util.Collection collection, int i)`
  void onChange3(
    bool z,
    jni.JObject collection,
    int i,
  ) {
    _onChange3(reference.pointer, _id_onChange3 as jni.JMethodIDPtr, z ? 1 : 0,
            collection.reference.pointer, i)
        .check();
  }

  static final _id_dispatchChange = _class.instanceMethodId(
    r'dispatchChange',
    r'(Z)V',
  );

  static final _dispatchChange = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JThrowablePtr Function(
                  ffi.Pointer<ffi.Void>,
                  jni.JMethodIDPtr,
                  ffi.VarArgs<($Int32,)>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni.JThrowablePtr Function(
              ffi.Pointer<ffi.Void>, jni.JMethodIDPtr, int)>();

  /// from: `public final void dispatchChange(boolean z)`
  void dispatchChange(
    bool z,
  ) {
    _dispatchChange(reference.pointer, _id_dispatchChange as jni.JMethodIDPtr,
            z ? 1 : 0)
        .check();
  }

  static final _id_dispatchChange1 = _class.instanceMethodId(
    r'dispatchChange',
    r'(ZLandroid/net/Uri;)V',
  );

  static final _dispatchChange1 = ProtectedJniExtensions.lookup<
              ffi.NativeFunction<
                  jni.JThrowablePtr Function(
                      ffi.Pointer<ffi.Void>,
                      jni.JMethodIDPtr,
                      ffi.VarArgs<($Int32, ffi.Pointer<ffi.Void>)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni.JThrowablePtr Function(ffi.Pointer<ffi.Void>, jni.JMethodIDPtr,
              int, ffi.Pointer<ffi.Void>)>();

  /// from: `public final void dispatchChange(boolean z, android.net.Uri uri)`
  void dispatchChange1(
    bool z,
    uri_.Uri uri,
  ) {
    _dispatchChange1(reference.pointer, _id_dispatchChange1 as jni.JMethodIDPtr,
            z ? 1 : 0, uri.reference.pointer)
        .check();
  }

  static final _id_dispatchChange2 = _class.instanceMethodId(
    r'dispatchChange',
    r'(ZLandroid/net/Uri;I)V',
  );

  static final _dispatchChange2 = ProtectedJniExtensions.lookup<
              ffi.NativeFunction<
                  jni.JThrowablePtr Function(
                      ffi.Pointer<ffi.Void>,
                      jni.JMethodIDPtr,
                      ffi.VarArgs<($Int32, ffi.Pointer<ffi.Void>, $Int32)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni.JThrowablePtr Function(ffi.Pointer<ffi.Void>, jni.JMethodIDPtr,
              int, ffi.Pointer<ffi.Void>, int)>();

  /// from: `public final void dispatchChange(boolean z, android.net.Uri uri, int i)`
  void dispatchChange2(
    bool z,
    uri_.Uri uri,
    int i,
  ) {
    _dispatchChange2(reference.pointer, _id_dispatchChange2 as jni.JMethodIDPtr,
            z ? 1 : 0, uri.reference.pointer, i)
        .check();
  }

  static final _id_dispatchChange3 = _class.instanceMethodId(
    r'dispatchChange',
    r'(ZLjava/util/Collection;I)V',
  );

  static final _dispatchChange3 = ProtectedJniExtensions.lookup<
              ffi.NativeFunction<
                  jni.JThrowablePtr Function(
                      ffi.Pointer<ffi.Void>,
                      jni.JMethodIDPtr,
                      ffi.VarArgs<($Int32, ffi.Pointer<ffi.Void>, $Int32)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni.JThrowablePtr Function(ffi.Pointer<ffi.Void>, jni.JMethodIDPtr,
              int, ffi.Pointer<ffi.Void>, int)>();

  /// from: `public final void dispatchChange(boolean z, java.util.Collection collection, int i)`
  void dispatchChange3(
    bool z,
    jni.JObject collection,
    int i,
  ) {
    _dispatchChange3(reference.pointer, _id_dispatchChange3 as jni.JMethodIDPtr,
            z ? 1 : 0, collection.reference.pointer, i)
        .check();
  }
}

final class $ContentObserverType extends jni.JObjType<ContentObserver> {
  const $ContentObserverType();

  @override
  String get signature => r'Landroid/database/ContentObserver;';

  @override
  ContentObserver fromReference(jni.JReference reference) =>
      ContentObserver.fromReference(reference);

  @override
  jni.JObjType get superType => const jni.JObjectType();

  @override
  final superCount = 1;

  @override
  int get hashCode => ($ContentObserverType).hashCode;

  @override
  bool operator ==(Object other) {
    return other.runtimeType == ($ContentObserverType) &&
        other is $ContentObserverType;
  }
}
