name: hybrid_vision_darwin
description: "iOS an macOS implementation of the hybrid_vision plugin."
version: 0.1.0
homepage: "https://github.com/yanshouwang/hybrid_sdk"

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  hybrid_vision_platform_interface: ^0.1.0
  ffi: ^2.1.0
  hybrid_core: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  ffigen: ^11.0.0

flutter:
  plugin:
    implements: hybrid_vision
    platforms:
      ios:
        ffiPlugin: true
        sharedDarwinSource: true
        dartPluginClass: HybridVisionDarwinPlugin
      macos:
        ffiPlugin: true
        sharedDarwinSource: true
        dartPluginClass: HybridVisionDarwinPlugin
