name: hybrid_os_linux
description: "Linux implementation of the hybrid_os plugin."
version: 0.0.2
repository: "https://github.com/yanshouwang/hybrid_sdk"

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hybrid_os_platform_interface: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  ffi: ^2.1.0
  ffigen: ^13.0.0

flutter:
  plugin:
    implements: hybrid_os
    platforms:
      linux:
        ffiPlugin: true
        dartPluginClass: HybridOSLinuxPlugin
