// Autogenerated by jnigen. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:ffi' as ffi;
import 'dart:isolate' show ReceivePort;

import 'package:jni/internal_helpers_for_jnigen.dart';
import 'package:jni/jni.dart' as jni;

import '../../../android/content/Intent.dart' as intent_;

/// from: `dev.hebei.hybrid_os_android.AndroidImpl$StartActivityCallback`
class AndroidImpl_StartActivityCallback extends jni.JObject {
  @override
  late final jni.JObjType<AndroidImpl_StartActivityCallback> $type = type;

  AndroidImpl_StartActivityCallback.fromReference(
    jni.JReference reference,
  ) : super.fromReference(reference);

  static final _class = jni.JClass.forName(
      r'dev/hebei/hybrid_os_android/AndroidImpl$StartActivityCallback');

  /// The type which includes information such as the signature of this class.
  static const type = $AndroidImpl_StartActivityCallbackType();
  static final _id_onActivityResult = _class.instanceMethodId(
    r'onActivityResult',
    r'()V',
  );

  static final _onActivityResult = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JThrowablePtr Function(
                ffi.Pointer<ffi.Void>,
                jni.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni.JThrowablePtr Function(
            ffi.Pointer<ffi.Void>,
            jni.JMethodIDPtr,
          )>();

  /// from: `public abstract void onActivityResult()`
  void onActivityResult() {
    _onActivityResult(
            reference.pointer, _id_onActivityResult as jni.JMethodIDPtr)
        .check();
  }

  /// Maps a specific port to the implemented interface.
  static final Map<int, $AndroidImpl_StartActivityCallbackImpl> _$impls = {};
  ReceivePort? _$p;

  static jni.JObjectPtr _$invoke(
    int port,
    jni.JObjectPtr descriptor,
    jni.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      $MethodInvocation.fromAddresses(
        0,
        descriptor.address,
        args.address,
      ),
    );
  }

  static final ffi.Pointer<
          ffi.NativeFunction<
              jni.JObjectPtr Function(
                  ffi.Uint64, jni.JObjectPtr, jni.JObjectPtr)>>
      _$invokePointer = ffi.Pointer.fromFunction(_$invoke);

  static ffi.Pointer<ffi.Void> _$invokeMethod(
    int $p,
    $MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onActivityResult()V') {
        _$impls[$p]!.onActivityResult();
        return jni.nullptr;
      }
    } catch (e) {
      return ProtectedJniExtensions.newDartException(e);
    }
    return jni.nullptr;
  }

  factory AndroidImpl_StartActivityCallback.implement(
    $AndroidImpl_StartActivityCallbackImpl $impl,
  ) {
    final $p = ReceivePort();
    final $x = AndroidImpl_StartActivityCallback.fromReference(
      ProtectedJniExtensions.newPortProxy(
        r'dev.hebei.hybrid_os_android.AndroidImpl$StartActivityCallback',
        $p,
        _$invokePointer,
      ),
    ).._$p = $p;
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
    $p.listen(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = $MethodInvocation.fromMessage($m as List<dynamic>);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      ProtectedJniExtensions.returnResult($i.result, $r);
    });
    return $x;
  }
}

abstract interface class $AndroidImpl_StartActivityCallbackImpl {
  factory $AndroidImpl_StartActivityCallbackImpl({
    required void Function() onActivityResult,
  }) = _$AndroidImpl_StartActivityCallbackImpl;

  void onActivityResult();
}

class _$AndroidImpl_StartActivityCallbackImpl
    implements $AndroidImpl_StartActivityCallbackImpl {
  _$AndroidImpl_StartActivityCallbackImpl({
    required void Function() onActivityResult,
  }) : _onActivityResult = onActivityResult;

  final void Function() _onActivityResult;

  void onActivityResult() {
    return _onActivityResult();
  }
}

final class $AndroidImpl_StartActivityCallbackType
    extends jni.JObjType<AndroidImpl_StartActivityCallback> {
  const $AndroidImpl_StartActivityCallbackType();

  @override
  String get signature =>
      r'Ldev/hebei/hybrid_os_android/AndroidImpl$StartActivityCallback;';

  @override
  AndroidImpl_StartActivityCallback fromReference(jni.JReference reference) =>
      AndroidImpl_StartActivityCallback.fromReference(reference);

  @override
  jni.JObjType get superType => const jni.JObjectType();

  @override
  final superCount = 1;

  @override
  int get hashCode => ($AndroidImpl_StartActivityCallbackType).hashCode;

  @override
  bool operator ==(Object other) {
    return other.runtimeType == ($AndroidImpl_StartActivityCallbackType) &&
        other is $AndroidImpl_StartActivityCallbackType;
  }
}

/// from: `dev.hebei.hybrid_os_android.AndroidImpl`
class AndroidImpl extends jni.JObject {
  @override
  late final jni.JObjType<AndroidImpl> $type = type;

  AndroidImpl.fromReference(
    jni.JReference reference,
  ) : super.fromReference(reference);

  static final _class =
      jni.JClass.forName(r'dev/hebei/hybrid_os_android/AndroidImpl');

  /// The type which includes information such as the signature of this class.
  static const type = $AndroidImplType();
  static final _id_INSTANCE = _class.staticFieldId(
    r'INSTANCE',
    r'Ldev/hebei/hybrid_os_android/AndroidImpl;',
  );

  /// from: `static public final dev.hebei.hybrid_os_android.AndroidImpl INSTANCE`
  /// The returned object must be released after use, by calling the [release] method.
  static AndroidImpl get INSTANCE =>
      _id_INSTANCE.get(_class, const $AndroidImplType());

  static final _id_startActivity = _class.instanceMethodId(
    r'startActivity',
    r'(Landroid/content/Intent;Ldev/hebei/hybrid_os_android/AndroidImpl$StartActivityCallback;)V',
  );

  static final _startActivity = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JThrowablePtr Function(
                  ffi.Pointer<ffi.Void>,
                  jni.JMethodIDPtr,
                  ffi.VarArgs<
                      (
                        ffi.Pointer<ffi.Void>,
                        ffi.Pointer<ffi.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni.JThrowablePtr Function(ffi.Pointer<ffi.Void>, jni.JMethodIDPtr,
              ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>();

  /// from: `public final void startActivity(android.content.Intent intent, dev.hebei.hybrid_os_android.AndroidImpl$StartActivityCallback startActivityCallback)`
  void startActivity(
    intent_.Intent intent,
    AndroidImpl_StartActivityCallback startActivityCallback,
  ) {
    _startActivity(reference.pointer, _id_startActivity as jni.JMethodIDPtr,
            intent.reference.pointer, startActivityCallback.reference.pointer)
        .check();
  }
}

final class $AndroidImplType extends jni.JObjType<AndroidImpl> {
  const $AndroidImplType();

  @override
  String get signature => r'Ldev/hebei/hybrid_os_android/AndroidImpl;';

  @override
  AndroidImpl fromReference(jni.JReference reference) =>
      AndroidImpl.fromReference(reference);

  @override
  jni.JObjType get superType => const jni.JObjectType();

  @override
  final superCount = 1;

  @override
  int get hashCode => ($AndroidImplType).hashCode;

  @override
  bool operator ==(Object other) {
    return other.runtimeType == ($AndroidImplType) && other is $AndroidImplType;
  }
}
