name: hybrid_os_windows
description: "Windows implementation of the hybrid_os plugin."
version: 0.0.1
repository: "https://github.com/yanshouwang/hybrid_sdk"

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  hybrid_os_platform_interface: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  ffigen: ^12.0.0

flutter:
  plugin:
    implements: hybrid_os
    platforms:
      windows:
        ffiPlugin: true
        dartPluginClass: HybridOSWindowsPlugin
