name: hybrid_media_android
description: "Android implementation of the hybrid_media plugin."
version: 0.0.1-dev.0
repository: "https://github.com/yanshouwang/hybrid_sdk"

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hybrid_logging: ^1.0.0
  hybrid_media_platform_interface: ^0.0.1-dev.1
  jni: ^0.11.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  jnigen: ^0.11.0

flutter:
  plugin:
    implements: hybrid_media
    platforms:
      android:
        ffiPlugin: true
        dartPluginClass: HybridMediaAndroidPlugin
        package: dev.hebei.hybrid_media_android
        pluginClass: HybridMediaAndroidPlugin

