name: hybrid_adb
description: "The ADB library of the Hybrid SDK."
version: 0.0.1
homepage: "https://github.com/yanshouwang/hybrid_sdk"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hybrid_adb_platform_interface:
    path: ../hybrid_adb_platform_interface
  hybrid_adb_windows:
    path: ../hybrid_adb_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      windows:
        default_package: hybrid_adb_windows