name: hybrid_uvc
description: 'The uvc library of the Hybrid SDK.'
version: 0.0.1-dev.0
repository: "https://github.com/yanshouwang/hybrid_sdk"

environment:
  sdk: ^3.1.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.3
  jni: ^0.11.0
  hybrid_jpeg: ^0.0.1-dev.0
  hybrid_usb: ^0.0.1-dev.0
  logging: ^1.2.0
  hybrid_logging: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  ffigen: ^13.0.0
  jnigen: ^0.11.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.hebei.hybrid_uvc
        pluginClass: HybridUVCPlugin
      # ios:
      #   pluginClass: HybridUvcPlugin
      linux:
        pluginClass: HybridUvcPlugin
      # macos:
      #   pluginClass: HybridUvcPlugin
      # windows:
      #   pluginClass: HybridUvcPluginCApi
      # web:
      #   pluginClass: HybridUvcWeb
      #   fileName: hybrid_uvc_web.dart
