// Autogenerated by jnigen. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:ffi' as ffi;
import 'dart:isolate' show ReceivePort;

import 'package:jni/internal_helpers_for_jnigen.dart';
import 'package:jni/jni.dart' as jni;

import 'Handler.dart' as handler_;

/// from: `android.os.Message`
class Message extends jni.JObject {
  @override
  late final jni.JObjType<Message> $type = type;

  Message.fromReference(
    jni.JReference reference,
  ) : super.fromReference(reference);

  static final _class = jni.JClass.forName(r'android/os/Message');

  /// The type which includes information such as the signature of this class.
  static const type = $MessageType();
  static final _id_CREATOR = _class.staticFieldId(
    r'CREATOR',
    r'Landroid/os/Parcelable$Creator;',
  );

  /// from: `static public final android.os.Parcelable$Creator CREATOR`
  /// The returned object must be released after use, by calling the [release] method.
  static jni.JObject get CREATOR =>
      _id_CREATOR.get(_class, const jni.JObjectType());

  static final _id_arg1 = _class.instanceFieldId(
    r'arg1',
    r'I',
  );

  /// from: `public int arg1`
  int get arg1 => _id_arg1.get(this, const jni.jintType());

  /// from: `public int arg1`
  set arg1(int value) => _id_arg1.set(this, const jni.jintType(), value);

  static final _id_arg2 = _class.instanceFieldId(
    r'arg2',
    r'I',
  );

  /// from: `public int arg2`
  int get arg2 => _id_arg2.get(this, const jni.jintType());

  /// from: `public int arg2`
  set arg2(int value) => _id_arg2.set(this, const jni.jintType(), value);

  static final _id_obj = _class.instanceFieldId(
    r'obj',
    r'Ljava/lang/Object;',
  );

  /// from: `public java.lang.Object obj`
  /// The returned object must be released after use, by calling the [release] method.
  jni.JObject get obj => _id_obj.get(this, const jni.JObjectType());

  /// from: `public java.lang.Object obj`
  /// The returned object must be released after use, by calling the [release] method.
  set obj(jni.JObject value) =>
      _id_obj.set(this, const jni.JObjectType(), value);

  static final _id_replyTo = _class.instanceFieldId(
    r'replyTo',
    r'Landroid/os/Messenger;',
  );

  /// from: `public android.os.Messenger replyTo`
  /// The returned object must be released after use, by calling the [release] method.
  jni.JObject get replyTo => _id_replyTo.get(this, const jni.JObjectType());

  /// from: `public android.os.Messenger replyTo`
  /// The returned object must be released after use, by calling the [release] method.
  set replyTo(jni.JObject value) =>
      _id_replyTo.set(this, const jni.JObjectType(), value);

  static final _id_sendingUid = _class.instanceFieldId(
    r'sendingUid',
    r'I',
  );

  /// from: `public int sendingUid`
  int get sendingUid => _id_sendingUid.get(this, const jni.jintType());

  /// from: `public int sendingUid`
  set sendingUid(int value) =>
      _id_sendingUid.set(this, const jni.jintType(), value);

  static final _id_what = _class.instanceFieldId(
    r'what',
    r'I',
  );

  /// from: `public int what`
  int get what => _id_what.get(this, const jni.jintType());

  /// from: `public int what`
  set what(int value) => _id_what.set(this, const jni.jintType(), value);

  static final _id_new0 = _class.constructorId(
    r'()V',
  );

  static final _new0 = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JniResult Function(
                ffi.Pointer<ffi.Void>,
                jni.JMethodIDPtr,
              )>>('globalEnv_NewObject')
      .asFunction<
          jni.JniResult Function(
            ffi.Pointer<ffi.Void>,
            jni.JMethodIDPtr,
          )>();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory Message() {
    return Message.fromReference(
        _new0(_class.reference.pointer, _id_new0 as jni.JMethodIDPtr)
            .reference);
  }

  static final _id_obtain = _class.staticMethodId(
    r'obtain',
    r'()Landroid/os/Message;',
  );

  static final _obtain = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JniResult Function(
                ffi.Pointer<ffi.Void>,
                jni.JMethodIDPtr,
              )>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni.JniResult Function(
            ffi.Pointer<ffi.Void>,
            jni.JMethodIDPtr,
          )>();

  /// from: `static public android.os.Message obtain()`
  /// The returned object must be released after use, by calling the [release] method.
  static Message obtain() {
    return _obtain(_class.reference.pointer, _id_obtain as jni.JMethodIDPtr)
        .object(const $MessageType());
  }

  static final _id_obtain1 = _class.staticMethodId(
    r'obtain',
    r'(Landroid/os/Message;)Landroid/os/Message;',
  );

  static final _obtain1 = ProtectedJniExtensions.lookup<
              ffi.NativeFunction<
                  jni.JniResult Function(
                      ffi.Pointer<ffi.Void>,
                      jni.JMethodIDPtr,
                      ffi.VarArgs<(ffi.Pointer<ffi.Void>,)>)>>(
          'globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni.JniResult Function(ffi.Pointer<ffi.Void>, jni.JMethodIDPtr,
              ffi.Pointer<ffi.Void>)>();

  /// from: `static public android.os.Message obtain(android.os.Message message)`
  /// The returned object must be released after use, by calling the [release] method.
  static Message obtain1(
    Message message,
  ) {
    return _obtain1(_class.reference.pointer, _id_obtain1 as jni.JMethodIDPtr,
            message.reference.pointer)
        .object(const $MessageType());
  }

  static final _id_obtain2 = _class.staticMethodId(
    r'obtain',
    r'(Landroid/os/Handler;)Landroid/os/Message;',
  );

  static final _obtain2 = ProtectedJniExtensions.lookup<
              ffi.NativeFunction<
                  jni.JniResult Function(
                      ffi.Pointer<ffi.Void>,
                      jni.JMethodIDPtr,
                      ffi.VarArgs<(ffi.Pointer<ffi.Void>,)>)>>(
          'globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni.JniResult Function(ffi.Pointer<ffi.Void>, jni.JMethodIDPtr,
              ffi.Pointer<ffi.Void>)>();

  /// from: `static public android.os.Message obtain(android.os.Handler handler)`
  /// The returned object must be released after use, by calling the [release] method.
  static Message obtain2(
    handler_.Handler handler,
  ) {
    return _obtain2(_class.reference.pointer, _id_obtain2 as jni.JMethodIDPtr,
            handler.reference.pointer)
        .object(const $MessageType());
  }

  static final _id_obtain3 = _class.staticMethodId(
    r'obtain',
    r'(Landroid/os/Handler;Ljava/lang/Runnable;)Landroid/os/Message;',
  );

  static final _obtain3 = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JniResult Function(
                  ffi.Pointer<ffi.Void>,
                  jni.JMethodIDPtr,
                  ffi.VarArgs<
                      (
                        ffi.Pointer<ffi.Void>,
                        ffi.Pointer<ffi.Void>
                      )>)>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni.JniResult Function(ffi.Pointer<ffi.Void>, jni.JMethodIDPtr,
              ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>();

  /// from: `static public android.os.Message obtain(android.os.Handler handler, java.lang.Runnable runnable)`
  /// The returned object must be released after use, by calling the [release] method.
  static Message obtain3(
    handler_.Handler handler,
    jni.JObject runnable,
  ) {
    return _obtain3(_class.reference.pointer, _id_obtain3 as jni.JMethodIDPtr,
            handler.reference.pointer, runnable.reference.pointer)
        .object(const $MessageType());
  }

  static final _id_obtain4 = _class.staticMethodId(
    r'obtain',
    r'(Landroid/os/Handler;I)Landroid/os/Message;',
  );

  static final _obtain4 = ProtectedJniExtensions.lookup<
              ffi.NativeFunction<
                  jni.JniResult Function(
                      ffi.Pointer<ffi.Void>,
                      jni.JMethodIDPtr,
                      ffi.VarArgs<(ffi.Pointer<ffi.Void>, $Int32)>)>>(
          'globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni.JniResult Function(ffi.Pointer<ffi.Void>, jni.JMethodIDPtr,
              ffi.Pointer<ffi.Void>, int)>();

  /// from: `static public android.os.Message obtain(android.os.Handler handler, int i)`
  /// The returned object must be released after use, by calling the [release] method.
  static Message obtain4(
    handler_.Handler handler,
    int i,
  ) {
    return _obtain4(_class.reference.pointer, _id_obtain4 as jni.JMethodIDPtr,
            handler.reference.pointer, i)
        .object(const $MessageType());
  }

  static final _id_obtain5 = _class.staticMethodId(
    r'obtain',
    r'(Landroid/os/Handler;ILjava/lang/Object;)Landroid/os/Message;',
  );

  static final _obtain5 = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JniResult Function(
                  ffi.Pointer<ffi.Void>,
                  jni.JMethodIDPtr,
                  ffi.VarArgs<
                      (
                        ffi.Pointer<ffi.Void>,
                        $Int32,
                        ffi.Pointer<ffi.Void>
                      )>)>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni.JniResult Function(ffi.Pointer<ffi.Void>, jni.JMethodIDPtr,
              ffi.Pointer<ffi.Void>, int, ffi.Pointer<ffi.Void>)>();

  /// from: `static public android.os.Message obtain(android.os.Handler handler, int i, java.lang.Object object)`
  /// The returned object must be released after use, by calling the [release] method.
  static Message obtain5(
    handler_.Handler handler,
    int i,
    jni.JObject object,
  ) {
    return _obtain5(_class.reference.pointer, _id_obtain5 as jni.JMethodIDPtr,
            handler.reference.pointer, i, object.reference.pointer)
        .object(const $MessageType());
  }

  static final _id_obtain6 = _class.staticMethodId(
    r'obtain',
    r'(Landroid/os/Handler;III)Landroid/os/Message;',
  );

  static final _obtain6 = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JniResult Function(
                  ffi.Pointer<ffi.Void>,
                  jni.JMethodIDPtr,
                  ffi.VarArgs<
                      (
                        ffi.Pointer<ffi.Void>,
                        $Int32,
                        $Int32,
                        $Int32
                      )>)>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni.JniResult Function(ffi.Pointer<ffi.Void>, jni.JMethodIDPtr,
              ffi.Pointer<ffi.Void>, int, int, int)>();

  /// from: `static public android.os.Message obtain(android.os.Handler handler, int i, int i1, int i2)`
  /// The returned object must be released after use, by calling the [release] method.
  static Message obtain6(
    handler_.Handler handler,
    int i,
    int i1,
    int i2,
  ) {
    return _obtain6(_class.reference.pointer, _id_obtain6 as jni.JMethodIDPtr,
            handler.reference.pointer, i, i1, i2)
        .object(const $MessageType());
  }

  static final _id_obtain7 = _class.staticMethodId(
    r'obtain',
    r'(Landroid/os/Handler;IIILjava/lang/Object;)Landroid/os/Message;',
  );

  static final _obtain7 = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JniResult Function(
                  ffi.Pointer<ffi.Void>,
                  jni.JMethodIDPtr,
                  ffi.VarArgs<
                      (
                        ffi.Pointer<ffi.Void>,
                        $Int32,
                        $Int32,
                        $Int32,
                        ffi.Pointer<ffi.Void>
                      )>)>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          jni.JniResult Function(ffi.Pointer<ffi.Void>, jni.JMethodIDPtr,
              ffi.Pointer<ffi.Void>, int, int, int, ffi.Pointer<ffi.Void>)>();

  /// from: `static public android.os.Message obtain(android.os.Handler handler, int i, int i1, int i2, java.lang.Object object)`
  /// The returned object must be released after use, by calling the [release] method.
  static Message obtain7(
    handler_.Handler handler,
    int i,
    int i1,
    int i2,
    jni.JObject object,
  ) {
    return _obtain7(_class.reference.pointer, _id_obtain7 as jni.JMethodIDPtr,
            handler.reference.pointer, i, i1, i2, object.reference.pointer)
        .object(const $MessageType());
  }

  static final _id_recycle = _class.instanceMethodId(
    r'recycle',
    r'()V',
  );

  static final _recycle = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JThrowablePtr Function(
                ffi.Pointer<ffi.Void>,
                jni.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni.JThrowablePtr Function(
            ffi.Pointer<ffi.Void>,
            jni.JMethodIDPtr,
          )>();

  /// from: `public void recycle()`
  void recycle() {
    _recycle(reference.pointer, _id_recycle as jni.JMethodIDPtr).check();
  }

  static final _id_copyFrom = _class.instanceMethodId(
    r'copyFrom',
    r'(Landroid/os/Message;)V',
  );

  static final _copyFrom = ProtectedJniExtensions.lookup<
              ffi.NativeFunction<
                  jni.JThrowablePtr Function(
                      ffi.Pointer<ffi.Void>,
                      jni.JMethodIDPtr,
                      ffi.VarArgs<(ffi.Pointer<ffi.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni.JThrowablePtr Function(ffi.Pointer<ffi.Void>, jni.JMethodIDPtr,
              ffi.Pointer<ffi.Void>)>();

  /// from: `public void copyFrom(android.os.Message message)`
  void copyFrom(
    Message message,
  ) {
    _copyFrom(reference.pointer, _id_copyFrom as jni.JMethodIDPtr,
            message.reference.pointer)
        .check();
  }

  static final _id_getWhen = _class.instanceMethodId(
    r'getWhen',
    r'()J',
  );

  static final _getWhen = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JniResult Function(
                ffi.Pointer<ffi.Void>,
                jni.JMethodIDPtr,
              )>>('globalEnv_CallLongMethod')
      .asFunction<
          jni.JniResult Function(
            ffi.Pointer<ffi.Void>,
            jni.JMethodIDPtr,
          )>();

  /// from: `public long getWhen()`
  int getWhen() {
    return _getWhen(reference.pointer, _id_getWhen as jni.JMethodIDPtr).long;
  }

  static final _id_setTarget = _class.instanceMethodId(
    r'setTarget',
    r'(Landroid/os/Handler;)V',
  );

  static final _setTarget = ProtectedJniExtensions.lookup<
              ffi.NativeFunction<
                  jni.JThrowablePtr Function(
                      ffi.Pointer<ffi.Void>,
                      jni.JMethodIDPtr,
                      ffi.VarArgs<(ffi.Pointer<ffi.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni.JThrowablePtr Function(ffi.Pointer<ffi.Void>, jni.JMethodIDPtr,
              ffi.Pointer<ffi.Void>)>();

  /// from: `public void setTarget(android.os.Handler handler)`
  void setTarget(
    handler_.Handler handler,
  ) {
    _setTarget(reference.pointer, _id_setTarget as jni.JMethodIDPtr,
            handler.reference.pointer)
        .check();
  }

  static final _id_getTarget = _class.instanceMethodId(
    r'getTarget',
    r'()Landroid/os/Handler;',
  );

  static final _getTarget = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JniResult Function(
                ffi.Pointer<ffi.Void>,
                jni.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni.JniResult Function(
            ffi.Pointer<ffi.Void>,
            jni.JMethodIDPtr,
          )>();

  /// from: `public android.os.Handler getTarget()`
  /// The returned object must be released after use, by calling the [release] method.
  handler_.Handler getTarget() {
    return _getTarget(reference.pointer, _id_getTarget as jni.JMethodIDPtr)
        .object(const handler_.$HandlerType());
  }

  static final _id_getCallback = _class.instanceMethodId(
    r'getCallback',
    r'()Ljava/lang/Runnable;',
  );

  static final _getCallback = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JniResult Function(
                ffi.Pointer<ffi.Void>,
                jni.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni.JniResult Function(
            ffi.Pointer<ffi.Void>,
            jni.JMethodIDPtr,
          )>();

  /// from: `public java.lang.Runnable getCallback()`
  /// The returned object must be released after use, by calling the [release] method.
  jni.JObject getCallback() {
    return _getCallback(reference.pointer, _id_getCallback as jni.JMethodIDPtr)
        .object(const jni.JObjectType());
  }

  static final _id_getData = _class.instanceMethodId(
    r'getData',
    r'()Landroid/os/Bundle;',
  );

  static final _getData = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JniResult Function(
                ffi.Pointer<ffi.Void>,
                jni.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni.JniResult Function(
            ffi.Pointer<ffi.Void>,
            jni.JMethodIDPtr,
          )>();

  /// from: `public android.os.Bundle getData()`
  /// The returned object must be released after use, by calling the [release] method.
  jni.JObject getData() {
    return _getData(reference.pointer, _id_getData as jni.JMethodIDPtr)
        .object(const jni.JObjectType());
  }

  static final _id_peekData = _class.instanceMethodId(
    r'peekData',
    r'()Landroid/os/Bundle;',
  );

  static final _peekData = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JniResult Function(
                ffi.Pointer<ffi.Void>,
                jni.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni.JniResult Function(
            ffi.Pointer<ffi.Void>,
            jni.JMethodIDPtr,
          )>();

  /// from: `public android.os.Bundle peekData()`
  /// The returned object must be released after use, by calling the [release] method.
  jni.JObject peekData() {
    return _peekData(reference.pointer, _id_peekData as jni.JMethodIDPtr)
        .object(const jni.JObjectType());
  }

  static final _id_setData = _class.instanceMethodId(
    r'setData',
    r'(Landroid/os/Bundle;)V',
  );

  static final _setData = ProtectedJniExtensions.lookup<
              ffi.NativeFunction<
                  jni.JThrowablePtr Function(
                      ffi.Pointer<ffi.Void>,
                      jni.JMethodIDPtr,
                      ffi.VarArgs<(ffi.Pointer<ffi.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni.JThrowablePtr Function(ffi.Pointer<ffi.Void>, jni.JMethodIDPtr,
              ffi.Pointer<ffi.Void>)>();

  /// from: `public void setData(android.os.Bundle bundle)`
  void setData(
    jni.JObject bundle,
  ) {
    _setData(reference.pointer, _id_setData as jni.JMethodIDPtr,
            bundle.reference.pointer)
        .check();
  }

  static final _id_sendToTarget = _class.instanceMethodId(
    r'sendToTarget',
    r'()V',
  );

  static final _sendToTarget = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JThrowablePtr Function(
                ffi.Pointer<ffi.Void>,
                jni.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni.JThrowablePtr Function(
            ffi.Pointer<ffi.Void>,
            jni.JMethodIDPtr,
          )>();

  /// from: `public void sendToTarget()`
  void sendToTarget() {
    _sendToTarget(reference.pointer, _id_sendToTarget as jni.JMethodIDPtr)
        .check();
  }

  static final _id_isAsynchronous = _class.instanceMethodId(
    r'isAsynchronous',
    r'()Z',
  );

  static final _isAsynchronous = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JniResult Function(
                ffi.Pointer<ffi.Void>,
                jni.JMethodIDPtr,
              )>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni.JniResult Function(
            ffi.Pointer<ffi.Void>,
            jni.JMethodIDPtr,
          )>();

  /// from: `public boolean isAsynchronous()`
  bool isAsynchronous() {
    return _isAsynchronous(
            reference.pointer, _id_isAsynchronous as jni.JMethodIDPtr)
        .boolean;
  }

  static final _id_setAsynchronous = _class.instanceMethodId(
    r'setAsynchronous',
    r'(Z)V',
  );

  static final _setAsynchronous = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JThrowablePtr Function(
                  ffi.Pointer<ffi.Void>,
                  jni.JMethodIDPtr,
                  ffi.VarArgs<($Int32,)>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni.JThrowablePtr Function(
              ffi.Pointer<ffi.Void>, jni.JMethodIDPtr, int)>();

  /// from: `public void setAsynchronous(boolean z)`
  void setAsynchronous(
    bool z,
  ) {
    _setAsynchronous(reference.pointer, _id_setAsynchronous as jni.JMethodIDPtr,
            z ? 1 : 0)
        .check();
  }

  static final _id_toString1 = _class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString1 = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JniResult Function(
                ffi.Pointer<ffi.Void>,
                jni.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni.JniResult Function(
            ffi.Pointer<ffi.Void>,
            jni.JMethodIDPtr,
          )>();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  jni.JString toString1() {
    return _toString1(reference.pointer, _id_toString1 as jni.JMethodIDPtr)
        .object(const jni.JStringType());
  }

  static final _id_describeContents = _class.instanceMethodId(
    r'describeContents',
    r'()I',
  );

  static final _describeContents = ProtectedJniExtensions.lookup<
          ffi.NativeFunction<
              jni.JniResult Function(
                ffi.Pointer<ffi.Void>,
                jni.JMethodIDPtr,
              )>>('globalEnv_CallIntMethod')
      .asFunction<
          jni.JniResult Function(
            ffi.Pointer<ffi.Void>,
            jni.JMethodIDPtr,
          )>();

  /// from: `public int describeContents()`
  int describeContents() {
    return _describeContents(
            reference.pointer, _id_describeContents as jni.JMethodIDPtr)
        .integer;
  }

  static final _id_writeToParcel = _class.instanceMethodId(
    r'writeToParcel',
    r'(Landroid/os/Parcel;I)V',
  );

  static final _writeToParcel = ProtectedJniExtensions.lookup<
              ffi.NativeFunction<
                  jni.JThrowablePtr Function(
                      ffi.Pointer<ffi.Void>,
                      jni.JMethodIDPtr,
                      ffi.VarArgs<(ffi.Pointer<ffi.Void>, $Int32)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni.JThrowablePtr Function(ffi.Pointer<ffi.Void>, jni.JMethodIDPtr,
              ffi.Pointer<ffi.Void>, int)>();

  /// from: `public void writeToParcel(android.os.Parcel parcel, int i)`
  void writeToParcel(
    jni.JObject parcel,
    int i,
  ) {
    _writeToParcel(reference.pointer, _id_writeToParcel as jni.JMethodIDPtr,
            parcel.reference.pointer, i)
        .check();
  }
}

final class $MessageType extends jni.JObjType<Message> {
  const $MessageType();

  @override
  String get signature => r'Landroid/os/Message;';

  @override
  Message fromReference(jni.JReference reference) =>
      Message.fromReference(reference);

  @override
  jni.JObjType get superType => const jni.JObjectType();

  @override
  final superCount = 1;

  @override
  int get hashCode => ($MessageType).hashCode;

  @override
  bool operator ==(Object other) {
    return other.runtimeType == ($MessageType) && other is $MessageType;
  }
}
