// Autogenerated by jnigen. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' show Object, String, bool, double, int;
import 'dart:core' as _$core;

import 'package:jni/_internal.dart' as _$jni;
import 'package:jni/jni.dart' as _$jni;

import 'Handler.dart' as handler_;

/// from: `android.os.Message`
class Message extends _$jni.JObject {
  @_$jni.internal
  @_$core.override
  final _$jni.JObjType<Message> $type;

  @_$jni.internal
  Message.fromReference(
    _$jni.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class = _$jni.JClass.forName(r'android/os/Message');

  /// The type which includes information such as the signature of this class.
  static const type = $Message$Type();
  static final _id_CREATOR = _class.staticFieldId(
    r'CREATOR',
    r'Landroid/os/Parcelable$Creator;',
  );

  /// from: `static public final android.os.Parcelable$Creator CREATOR`
  /// The returned object must be released after use, by calling the [release] method.
  static _$jni.JObject get CREATOR =>
      _id_CREATOR.get(_class, const _$jni.JObjectType());

  static final _id_arg1 = _class.instanceFieldId(
    r'arg1',
    r'I',
  );

  /// from: `public int arg1`
  int get arg1 => _id_arg1.get(this, const _$jni.jintType());

  /// from: `public int arg1`
  set arg1(int value) => _id_arg1.set(this, const _$jni.jintType(), value);

  static final _id_arg2 = _class.instanceFieldId(
    r'arg2',
    r'I',
  );

  /// from: `public int arg2`
  int get arg2 => _id_arg2.get(this, const _$jni.jintType());

  /// from: `public int arg2`
  set arg2(int value) => _id_arg2.set(this, const _$jni.jintType(), value);

  static final _id_obj = _class.instanceFieldId(
    r'obj',
    r'Ljava/lang/Object;',
  );

  /// from: `public java.lang.Object obj`
  /// The returned object must be released after use, by calling the [release] method.
  _$jni.JObject get obj => _id_obj.get(this, const _$jni.JObjectType());

  /// from: `public java.lang.Object obj`
  /// The returned object must be released after use, by calling the [release] method.
  set obj(_$jni.JObject value) =>
      _id_obj.set(this, const _$jni.JObjectType(), value);

  static final _id_replyTo = _class.instanceFieldId(
    r'replyTo',
    r'Landroid/os/Messenger;',
  );

  /// from: `public android.os.Messenger replyTo`
  /// The returned object must be released after use, by calling the [release] method.
  _$jni.JObject get replyTo => _id_replyTo.get(this, const _$jni.JObjectType());

  /// from: `public android.os.Messenger replyTo`
  /// The returned object must be released after use, by calling the [release] method.
  set replyTo(_$jni.JObject value) =>
      _id_replyTo.set(this, const _$jni.JObjectType(), value);

  static final _id_sendingUid = _class.instanceFieldId(
    r'sendingUid',
    r'I',
  );

  /// from: `public int sendingUid`
  int get sendingUid => _id_sendingUid.get(this, const _$jni.jintType());

  /// from: `public int sendingUid`
  set sendingUid(int value) =>
      _id_sendingUid.set(this, const _$jni.jintType(), value);

  static final _id_what = _class.instanceFieldId(
    r'what',
    r'I',
  );

  /// from: `public int what`
  int get what => _id_what.get(this, const _$jni.jintType());

  /// from: `public int what`
  set what(int value) => _id_what.set(this, const _$jni.jintType(), value);

  static final _id_new$ = _class.constructorId(
    r'()V',
  );

  static final _new$ = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_NewObject')
      .asFunction<
          _$jni.JniResult Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory Message() {
    return Message.fromReference(
        _new$(_class.reference.pointer, _id_new$ as _$jni.JMethodIDPtr)
            .reference);
  }

  static final _id_obtain = _class.staticMethodId(
    r'obtain',
    r'()Landroid/os/Message;',
  );

  static final _obtain = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          _$jni.JniResult Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `static public android.os.Message obtain()`
  /// The returned object must be released after use, by calling the [release] method.
  static Message obtain() {
    return _obtain(_class.reference.pointer, _id_obtain as _$jni.JMethodIDPtr)
        .object(const $Message$Type());
  }

  static final _id_obtain$1 = _class.staticMethodId(
    r'obtain',
    r'(Landroid/os/Message;)Landroid/os/Message;',
  );

  static final _obtain$1 = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JniResult Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Pointer<_$jni.Void>,)>)>>(
          'globalEnv_CallStaticObjectMethod')
      .asFunction<
          _$jni.JniResult Function(_$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr, _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public android.os.Message obtain(android.os.Message message)`
  /// The returned object must be released after use, by calling the [release] method.
  static Message obtain$1(
    Message message,
  ) {
    return _obtain$1(_class.reference.pointer,
            _id_obtain$1 as _$jni.JMethodIDPtr, message.reference.pointer)
        .object(const $Message$Type());
  }

  static final _id_obtain$2 = _class.staticMethodId(
    r'obtain',
    r'(Landroid/os/Handler;)Landroid/os/Message;',
  );

  static final _obtain$2 = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JniResult Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Pointer<_$jni.Void>,)>)>>(
          'globalEnv_CallStaticObjectMethod')
      .asFunction<
          _$jni.JniResult Function(_$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr, _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public android.os.Message obtain(android.os.Handler handler)`
  /// The returned object must be released after use, by calling the [release] method.
  static Message obtain$2(
    handler_.Handler handler,
  ) {
    return _obtain$2(_class.reference.pointer,
            _id_obtain$2 as _$jni.JMethodIDPtr, handler.reference.pointer)
        .object(const $Message$Type());
  }

  static final _id_obtain$3 = _class.staticMethodId(
    r'obtain',
    r'(Landroid/os/Handler;Ljava/lang/Runnable;)Landroid/os/Message;',
  );

  static final _obtain$3 = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          _$jni.JniResult Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public android.os.Message obtain(android.os.Handler handler, java.lang.Runnable runnable)`
  /// The returned object must be released after use, by calling the [release] method.
  static Message obtain$3(
    handler_.Handler handler,
    _$jni.JObject runnable,
  ) {
    return _obtain$3(
            _class.reference.pointer,
            _id_obtain$3 as _$jni.JMethodIDPtr,
            handler.reference.pointer,
            runnable.reference.pointer)
        .object(const $Message$Type());
  }

  static final _id_obtain$4 = _class.staticMethodId(
    r'obtain',
    r'(Landroid/os/Handler;I)Landroid/os/Message;',
  );

  static final _obtain$4 = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JniResult Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni
                          .VarArgs<(_$jni.Pointer<_$jni.Void>, _$jni.Int32)>)>>(
          'globalEnv_CallStaticObjectMethod')
      .asFunction<
          _$jni.JniResult Function(_$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr, _$jni.Pointer<_$jni.Void>, int)>();

  /// from: `static public android.os.Message obtain(android.os.Handler handler, int i)`
  /// The returned object must be released after use, by calling the [release] method.
  static Message obtain$4(
    handler_.Handler handler,
    int i,
  ) {
    return _obtain$4(_class.reference.pointer,
            _id_obtain$4 as _$jni.JMethodIDPtr, handler.reference.pointer, i)
        .object(const $Message$Type());
  }

  static final _id_obtain$5 = _class.staticMethodId(
    r'obtain',
    r'(Landroid/os/Handler;ILjava/lang/Object;)Landroid/os/Message;',
  );

  static final _obtain$5 = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          _$jni.JniResult Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              int,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public android.os.Message obtain(android.os.Handler handler, int i, java.lang.Object object)`
  /// The returned object must be released after use, by calling the [release] method.
  static Message obtain$5(
    handler_.Handler handler,
    int i,
    _$jni.JObject object,
  ) {
    return _obtain$5(
            _class.reference.pointer,
            _id_obtain$5 as _$jni.JMethodIDPtr,
            handler.reference.pointer,
            i,
            object.reference.pointer)
        .object(const $Message$Type());
  }

  static final _id_obtain$6 = _class.staticMethodId(
    r'obtain',
    r'(Landroid/os/Handler;III)Landroid/os/Message;',
  );

  static final _obtain$6 = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Int32
                      )>)>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          _$jni.JniResult Function(_$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr, _$jni.Pointer<_$jni.Void>, int, int, int)>();

  /// from: `static public android.os.Message obtain(android.os.Handler handler, int i, int i1, int i2)`
  /// The returned object must be released after use, by calling the [release] method.
  static Message obtain$6(
    handler_.Handler handler,
    int i,
    int i1,
    int i2,
  ) {
    return _obtain$6(
            _class.reference.pointer,
            _id_obtain$6 as _$jni.JMethodIDPtr,
            handler.reference.pointer,
            i,
            i1,
            i2)
        .object(const $Message$Type());
  }

  static final _id_obtain$7 = _class.staticMethodId(
    r'obtain',
    r'(Landroid/os/Handler;IIILjava/lang/Object;)Landroid/os/Message;',
  );

  static final _obtain$7 = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<
                      (
                        _$jni.Pointer<_$jni.Void>,
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Int32,
                        _$jni.Pointer<_$jni.Void>
                      )>)>>('globalEnv_CallStaticObjectMethod')
      .asFunction<
          _$jni.JniResult Function(
              _$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr,
              _$jni.Pointer<_$jni.Void>,
              int,
              int,
              int,
              _$jni.Pointer<_$jni.Void>)>();

  /// from: `static public android.os.Message obtain(android.os.Handler handler, int i, int i1, int i2, java.lang.Object object)`
  /// The returned object must be released after use, by calling the [release] method.
  static Message obtain$7(
    handler_.Handler handler,
    int i,
    int i1,
    int i2,
    _$jni.JObject object,
  ) {
    return _obtain$7(
            _class.reference.pointer,
            _id_obtain$7 as _$jni.JMethodIDPtr,
            handler.reference.pointer,
            i,
            i1,
            i2,
            object.reference.pointer)
        .object(const $Message$Type());
  }

  static final _id_recycle = _class.instanceMethodId(
    r'recycle',
    r'()V',
  );

  static final _recycle = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `public void recycle()`
  void recycle() {
    _recycle(reference.pointer, _id_recycle as _$jni.JMethodIDPtr).check();
  }

  static final _id_copyFrom = _class.instanceMethodId(
    r'copyFrom',
    r'(Landroid/os/Message;)V',
  );

  static final _copyFrom = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Pointer<_$jni.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(_$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr, _$jni.Pointer<_$jni.Void>)>();

  /// from: `public void copyFrom(android.os.Message message)`
  void copyFrom(
    Message message,
  ) {
    _copyFrom(reference.pointer, _id_copyFrom as _$jni.JMethodIDPtr,
            message.reference.pointer)
        .check();
  }

  static final _id_getWhen = _class.instanceMethodId(
    r'getWhen',
    r'()J',
  );

  static final _getWhen = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallLongMethod')
      .asFunction<
          _$jni.JniResult Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `public long getWhen()`
  int getWhen() {
    return _getWhen(reference.pointer, _id_getWhen as _$jni.JMethodIDPtr).long;
  }

  static final _id_setTarget = _class.instanceMethodId(
    r'setTarget',
    r'(Landroid/os/Handler;)V',
  );

  static final _setTarget = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Pointer<_$jni.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(_$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr, _$jni.Pointer<_$jni.Void>)>();

  /// from: `public void setTarget(android.os.Handler handler)`
  void setTarget(
    handler_.Handler handler,
  ) {
    _setTarget(reference.pointer, _id_setTarget as _$jni.JMethodIDPtr,
            handler.reference.pointer)
        .check();
  }

  static final _id_getTarget = _class.instanceMethodId(
    r'getTarget',
    r'()Landroid/os/Handler;',
  );

  static final _getTarget = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          _$jni.JniResult Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `public android.os.Handler getTarget()`
  /// The returned object must be released after use, by calling the [release] method.
  handler_.Handler getTarget() {
    return _getTarget(reference.pointer, _id_getTarget as _$jni.JMethodIDPtr)
        .object(const handler_.$Handler$Type());
  }

  static final _id_getCallback = _class.instanceMethodId(
    r'getCallback',
    r'()Ljava/lang/Runnable;',
  );

  static final _getCallback = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          _$jni.JniResult Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `public java.lang.Runnable getCallback()`
  /// The returned object must be released after use, by calling the [release] method.
  _$jni.JObject getCallback() {
    return _getCallback(
            reference.pointer, _id_getCallback as _$jni.JMethodIDPtr)
        .object(const _$jni.JObjectType());
  }

  static final _id_getData = _class.instanceMethodId(
    r'getData',
    r'()Landroid/os/Bundle;',
  );

  static final _getData = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          _$jni.JniResult Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `public android.os.Bundle getData()`
  /// The returned object must be released after use, by calling the [release] method.
  _$jni.JObject getData() {
    return _getData(reference.pointer, _id_getData as _$jni.JMethodIDPtr)
        .object(const _$jni.JObjectType());
  }

  static final _id_peekData = _class.instanceMethodId(
    r'peekData',
    r'()Landroid/os/Bundle;',
  );

  static final _peekData = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          _$jni.JniResult Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `public android.os.Bundle peekData()`
  /// The returned object must be released after use, by calling the [release] method.
  _$jni.JObject peekData() {
    return _peekData(reference.pointer, _id_peekData as _$jni.JMethodIDPtr)
        .object(const _$jni.JObjectType());
  }

  static final _id_setData = _class.instanceMethodId(
    r'setData',
    r'(Landroid/os/Bundle;)V',
  );

  static final _setData = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni.VarArgs<(_$jni.Pointer<_$jni.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(_$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr, _$jni.Pointer<_$jni.Void>)>();

  /// from: `public void setData(android.os.Bundle bundle)`
  void setData(
    _$jni.JObject bundle,
  ) {
    _setData(reference.pointer, _id_setData as _$jni.JMethodIDPtr,
            bundle.reference.pointer)
        .check();
  }

  static final _id_sendToTarget = _class.instanceMethodId(
    r'sendToTarget',
    r'()V',
  );

  static final _sendToTarget = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `public void sendToTarget()`
  void sendToTarget() {
    _sendToTarget(reference.pointer, _id_sendToTarget as _$jni.JMethodIDPtr)
        .check();
  }

  static final _id_isAsynchronous = _class.instanceMethodId(
    r'isAsynchronous',
    r'()Z',
  );

  static final _isAsynchronous = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallBooleanMethod')
      .asFunction<
          _$jni.JniResult Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `public boolean isAsynchronous()`
  bool isAsynchronous() {
    return _isAsynchronous(
            reference.pointer, _id_isAsynchronous as _$jni.JMethodIDPtr)
        .boolean;
  }

  static final _id_setAsynchronous = _class.instanceMethodId(
    r'setAsynchronous',
    r'(Z)V',
  );

  static final _setAsynchronous = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JThrowablePtr Function(
                  _$jni.Pointer<_$jni.Void>,
                  _$jni.JMethodIDPtr,
                  _$jni.VarArgs<(_$jni.Int32,)>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(
              _$jni.Pointer<_$jni.Void>, _$jni.JMethodIDPtr, int)>();

  /// from: `public void setAsynchronous(boolean z)`
  void setAsynchronous(
    bool z,
  ) {
    _setAsynchronous(reference.pointer,
            _id_setAsynchronous as _$jni.JMethodIDPtr, z ? 1 : 0)
        .check();
  }

  static final _id_toString$1 = _class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          _$jni.JniResult Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `public java.lang.String toString()`
  /// The returned object must be released after use, by calling the [release] method.
  _$jni.JString toString$1() {
    return _toString$1(reference.pointer, _id_toString$1 as _$jni.JMethodIDPtr)
        .object(const _$jni.JStringType());
  }

  static final _id_describeContents = _class.instanceMethodId(
    r'describeContents',
    r'()I',
  );

  static final _describeContents = _$jni.ProtectedJniExtensions.lookup<
          _$jni.NativeFunction<
              _$jni.JniResult Function(
                _$jni.Pointer<_$jni.Void>,
                _$jni.JMethodIDPtr,
              )>>('globalEnv_CallIntMethod')
      .asFunction<
          _$jni.JniResult Function(
            _$jni.Pointer<_$jni.Void>,
            _$jni.JMethodIDPtr,
          )>();

  /// from: `public int describeContents()`
  int describeContents() {
    return _describeContents(
            reference.pointer, _id_describeContents as _$jni.JMethodIDPtr)
        .integer;
  }

  static final _id_writeToParcel = _class.instanceMethodId(
    r'writeToParcel',
    r'(Landroid/os/Parcel;I)V',
  );

  static final _writeToParcel = _$jni.ProtectedJniExtensions.lookup<
              _$jni.NativeFunction<
                  _$jni.JThrowablePtr Function(
                      _$jni.Pointer<_$jni.Void>,
                      _$jni.JMethodIDPtr,
                      _$jni
                          .VarArgs<(_$jni.Pointer<_$jni.Void>, _$jni.Int32)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          _$jni.JThrowablePtr Function(_$jni.Pointer<_$jni.Void>,
              _$jni.JMethodIDPtr, _$jni.Pointer<_$jni.Void>, int)>();

  /// from: `public void writeToParcel(android.os.Parcel parcel, int i)`
  void writeToParcel(
    _$jni.JObject parcel,
    int i,
  ) {
    _writeToParcel(reference.pointer, _id_writeToParcel as _$jni.JMethodIDPtr,
            parcel.reference.pointer, i)
        .check();
  }
}

final class $Message$Type extends _$jni.JObjType<Message> {
  @_$jni.internal
  const $Message$Type();

  @_$jni.internal
  @_$core.override
  String get signature => r'Landroid/os/Message;';

  @_$jni.internal
  @_$core.override
  Message fromReference(_$jni.JReference reference) =>
      Message.fromReference(reference);

  @_$jni.internal
  @_$core.override
  _$jni.JObjType get superType => const _$jni.JObjectType();

  @_$jni.internal
  @_$core.override
  final superCount = 1;

  @_$core.override
  int get hashCode => ($Message$Type).hashCode;

  @_$core.override
  bool operator ==(Object other) {
    return other.runtimeType == ($Message$Type) && other is $Message$Type;
  }
}
