name: hybrid_core_darwin
description: "iOS an macOS implementation of the hybrid_core plugin."
version: 0.5.0
homepage: "https://github.com/yanshouwang/hybrid_sdk"

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hybrid_core_platform_interface: ^0.5.0
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  ffigen: ^11.0.0

flutter:
  plugin:
    implements: hybrid_core
    platforms:
      ios:
        ffiPlugin: true
        sharedDarwinSource: true
        dartPluginClass: HybridCoreDarwinPlugin
      macos:
        ffiPlugin: true
        sharedDarwinSource: true
        dartPluginClass: HybridCoreDarwinPlugin
