name: hybrid_os_platform_interface
description: "A common platform interface for the hybrid_os plugin."
version: 0.1.0-dev.0
repository: "https://github.com/yanshouwang/hybrid_sdk"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
