name: hybrid_os
description: "The os library of the Hybrid SDK."
version: 0.0.1
repository: "https://github.com/yanshouwang/hybrid_sdk"

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter
  hybrid_os_platform_interface: ^0.0.1
  hybrid_os_android: ^0.0.1
  hybrid_os_darwin: ^0.0.1
  hybrid_os_windows: ^0.0.1
  hybrid_os_linux: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: hybrid_os_android
      ios:
        default_package: hybrid_os_darwin
      macos:
        default_package: hybrid_os_darwin
      windows:
        default_package: hybrid_os_windows
      linux:
        default_package: hybrid_os_linux
