name: hybrid_core
description: "The core library of the Hybrid SDK."
version: 0.5.1
homepage: "https://github.com/yanshouwang/hybrid_sdk"

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hybrid_core_platform_interface: ^0.5.0
  hybrid_core_android: ^0.5.2
  hybrid_core_darwin: ^0.5.0
  hybrid_core_windows: ^0.5.2
  hybrid_core_linux: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: hybrid_core_android
      ios:
        default_package: hybrid_core_darwin
      macos:
        default_package: hybrid_core_darwin
      windows:
        default_package: hybrid_core_windows
      linux: 
        default_package: hybrid_core_linux
